name:
  "lms-testing"

# docker-compose.yml
services:
  floci:
    image: hectorvent/floci:latest
    ports:
      - "4566:4566"
    volumes:
      - ./floci-data:/app/data
    network_mode: "host"
    
  
  video-worker:
    build:
      context: .
      dockerfile: apps/video-processing/Dockerfile
    depends_on:
      - floci
    environment:
      AWS_ENDPOINT_URL: http://172.17.0.1:4566
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    env_file:
      - .env.local
    volumes:
      - ./worker-data:/data
    network_mode: "host"


volumes:
 floci-data:

